# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 537f9de6a1155603891b872d8d45037974be83673f8ca1e561808e13dd004cbc180679266fea98c4c3d543953ddfebf56c14292b517d2302a955b85309d11cf0

test:
  secret_key_base: 81d13b8bc625a1267a5f7a01790443bb73a3fd76ff5a8eadd6ce9ac359c4a0df1b7493d160cbe1dad762b2a5f0f0d482d6ecc1bab83bc74d3417e8c1750b6a1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
